using System;
using System.Collections.Generic;
using System.Web;

namespace asf.cms.model
{
    public class EspecialesVO
    {
        public virtual int Id
        {
            set;
            get;
        }
        public virtual int LanguageId
        {
            set;
            get;
        }
        public virtual int SectionId
        {
            set;
            get;
        }
        public virtual String Permalink
        {
            set;
            get;
        }
        public virtual String Title
        {
            set;
            get;
        }
        public virtual DateTime Created
        {
            set;
            get;
        }
        public virtual DateTime Updated
        {
            set;
            get;
        }
        public virtual DateTime Published
        {
            set;
            get;
        }
        public virtual bool IsMain
        {
            set;
            get;
        }
        public virtual String Content
        {
            set;
            get;
        }
        public virtual int IsAutogenerated
        {
            set;
            get;
        }
        public virtual String AutogeneratedType
        {
            set;
            get;
        }
        public virtual DateTime Unpublished
        {
            set;
            get;
        }
        public virtual int Status
        {
            set;
            get;
        }
        public virtual int Visitas
        {
            set;
            get;
        }
        public virtual bool HasWidgets
        {
            set;
            get;
        }
        public virtual bool NewsInclude
        {
            set;
            get;
        }
        public virtual bool NewsPin
        {
            set;
            get;
        }
        public virtual int NewsTTL
        {
            set;
            get;
        }
        public virtual string NewsContent
        {
            set;
            get;
        }
        public virtual bool NewsIncludeInSection
        {
            set;
            get;
        }

        public virtual int Position
        {
            set;
            get;
        }
        public virtual Boolean Active
        {
            set;
            get;
        }
        public virtual String Meta
        {
            set;
            get;
        }
        public virtual bool SitemapExclude
        {
            set;
            get;
        }
    }
}
