using System;
using System.Collections.Generic;
using System.Web;

namespace asf.cms.model
{
    public class EspecialesAdminVO
    {
        public bool IsMain {  get { return isMain == 1; } }
        public bool SitemapExclude { get { return _sitemapExclude == 1; } }
        public virtual int Id { set; get; }
        public virtual string Title { set; get; }
        public virtual int LanguageId { set; get; }
        public virtual string Section { set; get; }
        public virtual int isMain { set; get; }
        public virtual uint Status { set; get; }
        public virtual string AutogeneratedType { set; get; }
        public virtual int _sitemapExclude { set; get; }

        public static int CompareBySection(EspecialesAdminVO a, EspecialesAdminVO b)
        {
            return string.Compare(a.Section, b.Section);
        }
    }
}
