using System;
using System.Collections.Generic;
using System.Web;

namespace asf.cms.model
{
    public class PublicationAdminVO
    {
        public bool IsMain {
#if MYSQL32
            get { return _isMain == 1; }
            set { _isMain = value ? (SByte)1 : (SByte)0; }
#else
            set; get;
#endif
        }
        public bool SitemapExclude {
#if MYSQL32
            get { return _sitemapExclude == (SByte)1; }
            set { _sitemapExclude = value ? (SByte)1 : (SByte)0; }
#else
            set; get;
#endif
        }
        public virtual int Id { set; get; }
        public virtual string Title { set; get; }
        public virtual int LanguageId { set; get; }
        public virtual string Section { set; get; }
#if MYSQL32
        public virtual SByte _isMain { set; get; }
        public virtual SByte _sitemapExclude { set; get; }
#endif
        public virtual uint Status { set; get; }
        public virtual string AutogeneratedType { set; get; }
        public virtual uint Position { set; get; }
        public static int CompareBySection(PublicationAdminVO a, PublicationAdminVO b)
        {
            return string.Compare(a.Section, b.Section);
        }
    }
}
