<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="List.aspx.cs" Inherits="asf.cms.view.sectionSpecial.List" ValidateRequest="false" MasterPageFile="~/view/master/Admin.Master" EnableViewState="false" %>
<%@ Register Src="../ContentAddModal.ascx" TagName="ContentAddModal" TagPrefix="asfcms" %>

<%@ Import Namespace="System.Collections.Generic" %>
<%@ Import Namespace="asf.cms.bll" %>

<asp:Content ContentPlaceHolderID="head" ID="h" runat="server">
   <script type="text/javascript" src="../view/js/admin/v3/publication/PublicationSpecialSectionList.js"></script>

    <%
    if (((asf.cms.model.UserVO)Session["User"]).Type == "ADMIN")
    {
        %>
        <script type="text/javascript" src="../view/js/admin/v3/ContentAdd.js"></script>
        <script type="text/javascript">
            var addEnable = true;
        </script>
        <%
    }
    %>
</asp:Content>

<asp:Content ContentPlaceHolderID="contenido" ID="cont"  runat="server">
    <div class="contenido_b">

        <h2>Secciones especiales</h2>
    <%
    if (GetMessage("userType") == "ADMIN")
    {
        %>

        <h4>Especiales</h4>
        <input id="sectionId-especiales" name="sectionId" type="hidden" value="81" />
        <table id="publicationList-especiales" class="ui celled unstackable table" style="width: 100%"></table>

        <%
    }

    List<Section> sections = GetRequestVar("specialSections") as List<Section>;

    foreach(Section section in sections)
    {
        %>
        <h4><%=section.Title %></h4>
        <input id="sectionId-<%=section.Type %>" name="sectionId" type="hidden" value="<%=section.SectionId %>" />
        <table id="publicationList-<%=section.Type %>" class="ui celled unstackable table" style="width: 100%"></table>
        <%
    }
%>

<%
    if (GetMessage("userType") == "ADMIN")
    {
        %>
            <asfcms:ContentAddModal ID="SectionAddModal" runat="Server" />
	    <%
    }
%>
    </div>

    <!--
    <div id="newPublicationPopUp" style="font-size:12px !important">
        <form id="frmNewPublicaitionPopUp" action="Insert" method="post">
            <input type="hidden" name="sectionId" id="sectionIdNewPublication" value="" />
            <input type="hidden" name="autogenerated_type" id="typeNewPublication" value="" />
            <table cellpadding="6" width="80%">
                <tr>
                    <td>Titulo:</td>
                    <td>
                        <input type="text" name="title" id="titleNewPublication" size="45"  />
                    </td>
               </tr>
                <tr>
                    <td>Permalink:</td>
                    <td><input type="text" name="permalink" id="permalinkNewPublication" readonly="readonly" class="readonly" size="45"/></td>
                </tr>
            </table>
        </form>
    </div>
    -->
</asp:Content>
