//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asf.cms.view.widgets.ui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WidgetTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WidgetTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("asf.cms.view.widgets.ui.WidgetTemplates", typeof(WidgetTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div align=&quot;center&quot;&gt;&lt;object classid=&quot;clsid:D27CDB6E-AE6D-11cf-96B8-444553540000&quot; width=&quot;210&quot; height=&quot;176&quot;  codebase=&quot;http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0&quot;&gt;
        ///	&lt;param name=&quot;src&quot; value=&quot;@AnnouncePlayerSWF&quot; /&gt;
        ///	&lt;param name=&quot;bgcolor&quot; value=&quot;#000000&quot; /&gt;
        ///	&lt;param name=&quot;quality&quot; value=&quot;high&quot; /&gt;
        ///	&lt;param name=&quot;FlashVars&quot; value=&quot;@AnnounceFlashVars&quot; /&gt;
        ///	&lt;embed FlashVars=&quot;@AnnounceFlashVars&quot; type=&quot;application/x-shockwave-flash&quot; width=&quot;210&quot; height=&quot;176&quot; src=&quot;@AnnouncePla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AnnounceWidgetTemplate {
            get {
                return ResourceManager.GetString("AnnounceWidgetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color:#fff;background:#000;padding:4&quot;&gt;@ActualCount&lt;/span&gt;.
        /// </summary>
        internal static string CounterWidgetTemplate
        {
            get
            {
                return ResourceManager.GetString("CounterWidgetTemplate", resourceCulture);
            }
        }
        internal static string RecuperacionWidgetTemplate
        {
            get
            {
                return ResourceManager.GetString("RecuperacionWidgetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;widgets_map&quot;&gt;
        ///@MapStructure
        ///&lt;/span&gt;.
        /// </summary>
        internal static string MapWidgetTemplate {
            get {
                return ResourceManager.GetString("MapWidgetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;widgets_modification&quot;&gt;@ModificationDate&lt;/span&gt;.
        /// </summary>
        internal static string ModificationWidgetTemplate {
            get {
                return ResourceManager.GetString("ModificationWidgetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;news_table&quot;&gt;
        ///    #$
        ///    &lt;tr&gt;
        ///        &lt;td&gt;&lt;/td&gt;
        ///        &lt;td&gt;&lt;a href=&quot;@NewsPermalink&quot;&gt;@NewsTitle&lt;/a&gt;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    @NewsContentRow
        ///    $#
        ///&lt;/table&gt;.
        /// </summary>
        internal static string NewsWidgetTemplate {
            get {
                return ResourceManager.GetString("NewsWidgetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;rss xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot; xmlns:itunes=&quot;http://www.itunes.com/dtds/podcast-1.0.dtd&quot;
        ///	version=&quot;2.0&quot; xmlns:media=&quot;http://search.yahoo.com/mrss/&quot;&gt;
        ///	&lt;channel&gt;
        ///		&lt;title&gt;@RSSTitle&lt;/title&gt;
        ///		&lt;link&gt;@RSSLink&lt;/link&gt;
        ///		&lt;description&gt;@RSSDescription&lt;/description&gt;
        ///		&lt;atom:link href=&quot;@RSSAtomLink&quot; rel=&quot;self&quot;&gt;&lt;/atom:link&gt;
        ///		&lt;language&gt;@RSSLanguage&lt;/language&gt;
        ///		&lt;lastBuildDate&gt;@RSSLastBuildDate&lt;/lastBuildDate&gt;
        ///		&lt;pubDate&gt;@RSSPubDate&lt;/pubDate&gt;
        ///		#$
        ///		&lt;item&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VideoRSSTemplate {
            get {
                return ResourceManager.GetString("VideoRSSTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;object classid=&quot;clsid:D27CDB6E-AE6D-11cf-96B8-444553540000&quot; width=&quot;560&quot; height=&quot;420&quot; codebase=&quot;http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0&quot;&gt;
        ///	&lt;param name=&quot;src&quot; value=&quot;@VideoPlayerSWF&quot; /&gt;
        ///                   &lt;param name=&quot;allowFullScreen&quot; value=&quot;true&quot; /&gt;
        ///	&lt;param name=&quot;bgcolor&quot; value=&quot;#000000&quot; /&gt;
        ///	&lt;param name=&quot;quality&quot; value=&quot;high&quot; /&gt;
        ///	&lt;param name=&quot;FlashVars&quot; value=&quot;type=@type&amp;fullscreen=true&amp;playlist=@playlist&amp;rssUrl=@rssURIHandler&quot; /&gt;
        ///	&lt;embed FlashVars=&quot;type=@ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VideoWidgetTemplate {
            get {
                return ResourceManager.GetString("VideoWidgetTemplate", resourceCulture);
            }
        }
    }
}
